# netlify.toml
[build]
command = ""
publish = "."

# Make branch deploys predictable
[build.environment]
HUGO_VERSION = ""  # (ignore – just keeps Netlify happy)

# Cache-bust everything so updates are visible immediately
[[headers]]
for = "/*"
  [headers.values]
  Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"

# Context-specific settings (optional)
[context.production]
  publish = "."

[context.deploy-preview]
  publish = "."

[context.branch-deploy]
  publish = "."
